### ISSUE TITLE
Issue Client website html

### ISSUE THREAD

**Issue by FatimaZelay** [DivaniNL/red-pers#2]
Je html ziet er goed uit! Je code is goed uitgevoerd. Je zou eventueel bij rij 1 de taal veranderen, de tekst is geschreven in het nederlands maar je geeft aan het in het engels te hebben geschreven. 

Hier kan je zien waar ik het over heb https://validator.w3.org/nu/?doc=https%3A%2F%2Fdivaninl.github.io%2Fred-pers%2Findex.html

**Comment by DivaniNL** [comment]
Is aangepast : )
[zie hier](https://github.com/DivaniNL/red-pers/commit/a7b86a46726242d7721fc5c360abb15fcefd0907)
