### ISSUE TITLE
issue red-pers

### ISSUE THREAD

**Issue by OFRqq** [DivaniNL/red-pers#3]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdivaninl.github.io%2Fred-pers%2F

Zie geen dingen die voor problemen zorgen, eventueel lang aanpassen en = nl.

**Comment by DivaniNL** [comment]
Is aangepast : )
[zie hier](https://github.com/DivaniNL/red-pers/commit/a7b86a46726242d7721fc5c360abb15fcefd0907)
