### ISSUE TITLE
Vermijd dubbele content in je code

### ISSUE THREAD

**Issue by joostf** [DivaniNL/red-pers#4]
https://github.com/DivaniNL/red-pers/blob/a7b86a46726242d7721fc5c360abb15fcefd0907/index.html#L10-L81

Je hebt dubbele content voor je navigatie in je HTML staan (voor mobile én desktop). Dat is om meerdere redenen geen goed idee; toegankelijkheid, onderhoudbaarheid, etc.

Maak één navigatie en los de presentatie responsive op met CSS

**Comment by DivaniNL** [comment]
Ik ga dit volgende sprint oppakken. Het is te kort dag aangezien ik nog JS code moet toevoegen

**Comment by DivaniNL** [comment]
fixed!
https://github.com/DivaniNL/all-human-accessible-website/commit/a7dd2753c6c16aafc50a283876df650fde08ca12
https://github.com/DivaniNL/all-human-accessible-website/commit/efdfd0788410f85275fc6953022e0bef381f51f5
