### ISSUE TITLE
Zorg ervoor dat al je section elementen een heading hebben

### ISSUE THREAD

**Issue by joostf** [DivaniNL/red-pers#5]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdivaninl.github.io%2Fred-pers%2F

Lees nog eens dit artikel over hoe je section elementen gebruikt om je HTML te structureren
https://css-tricks.com/how-to-section-your-html/#aa-sectioning-elements-and-the-document-outline-algorithm

**Comment by joostf** [comment]
De structuur van je HTML is niet overal even logisch.  Het is belangrijk om de structuur van de content helemaal goed te krijgen voordat je gaat stylen met CSS. Mijn tip zou zijn om nog eens heel nauwkeurig de breakdown van je ontwerp naar HTML te schetsen.

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/red-pers/commit/f635070576b97f28c9ab79030a703ec52c3b689f
Ik heb van sections die niet een header direct erin hebben een div gemaakt

**Comment by joostf** [comment]
Ik denk niet dat dat de juiste keuze is. 
Dat bij een sectie op de website geen heading (zichtbaar) staat, betekent niet dat er geen heading in de HTML hoeft te staan. Voor mensen die niet (goed) kunnen zien en een screen reader gebruiken om een website te kunnen bezoeken, is het heel belangrijk dat ze kunnen zien welke 'hoofdstukken' (sections) een website bevat en wat de titel (heading) is van elk hoofdstuk. Voor search engines is het overigens ook beter als je HTML duidelijk gestructureerd is!

Een bezoeker die je website wel kan bekijken hoeft niet altijd alle titels te zien, dus je kan met CSS de headings visueel verbergen.

Meer info: https://www.a11yproject.com/posts/how-to-hide-content/

**Comment by DivaniNL** [comment]
Ah ik dacht dat dat soort dingen not done waren.
Ik kan dit doorvoeren

**Comment by joostf** [comment]
Dat soor dingen zijn juist **done** 🤗
In [Sprint 3 All Human](https://programma.fdnd.nl/static-web/all-human) komen we er nog uitgebreid op terug!

**Comment by DivaniNL** [comment]
[Hier heb ik de inleidende hidden titel toegevoegd](https://github.com/DivaniNL/all-human-accessible-website/commit/5656d0719c36679ed7011f0fde26ecd22d60a156)
