### ISSUE TITLE
Wat is de titel (heading) van dit article element?

### ISSUE THREAD

**Issue by joostf** [DivaniNL/red-pers#6]
https://github.com/DivaniNL/red-pers/blob/a7b86a46726242d7721fc5c360abb15fcefd0907/index.html#L108

**Comment by DivaniNL** [comment]
Ah, zal ik hier een DIV van maken of een ander element?
In het design staat hier namelijk geen titel, dus een section of article mag hier bijv. niet.

Wat zou hier uw elementkeuze zijn?

**Comment by DivaniNL** [comment]
Deze is inmiddels toegevoegd
